apiVersion: v1
kind: ConfigMap
metadata:
  name: vakta-config
data:
  config.yaml: |
    agent:
      mode: {{ .Values.mode }}
    sources:
      ebpf: true
      auditd: false
      k8s_audit: true
      k8s_audit_log: /var/log/k8s-audit.log
    rules_dir: /etc/vakta/rules
    actions_dir: /etc/vakta/actions
    outputs:
      alertmanager: "{{ .Values.alertmanager }}"
      loki: "{{ .Values.loki }}"
    storage:
      sqlite_path: /var/lib/vakta/events.db
      retention_days: 30
    ui:
      enabled: true
      addr: ":9090"
      auth: none
