// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	probeMapDrops                   = "drops"
	probeMapEvents                  = "events"
	probeProgHandleSchedExec        = "handle_sched_exec"
	probeProgHandleSysEnterClone    = "handle_sys_enter_clone"
	probeProgHandleSysEnterClone3   = "handle_sys_enter_clone3"
	probeProgHandleSysEnterConnect  = "handle_sys_enter_connect"
	probeProgHandleSysEnterExecve   = "handle_sys_enter_execve"
	probeProgHandleSysEnterExecveat = "handle_sys_enter_execveat"
	probeProgHandleSysEnterOpen     = "handle_sys_enter_open"
	probeProgHandleSysEnterOpenat   = "handle_sys_enter_openat"
	probeProgHandleSysEnterUnshare  = "handle_sys_enter_unshare"
)

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	HandleSchedExec        *ebpf.ProgramSpec `ebpf:"handle_sched_exec"`
	HandleSysEnterClone    *ebpf.ProgramSpec `ebpf:"handle_sys_enter_clone"`
	HandleSysEnterClone3   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_clone3"`
	HandleSysEnterConnect  *ebpf.ProgramSpec `ebpf:"handle_sys_enter_connect"`
	HandleSysEnterExecve   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_execve"`
	HandleSysEnterExecveat *ebpf.ProgramSpec `ebpf:"handle_sys_enter_execveat"`
	HandleSysEnterOpen     *ebpf.ProgramSpec `ebpf:"handle_sys_enter_open"`
	HandleSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_openat"`
	HandleSysEnterUnshare  *ebpf.ProgramSpec `ebpf:"handle_sys_enter_unshare"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	Drops  *ebpf.MapSpec `ebpf:"drops"`
	Events *ebpf.MapSpec `ebpf:"events"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	Drops  *ebpf.Map `ebpf:"drops"`
	Events *ebpf.Map `ebpf:"events"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.Drops,
		m.Events,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	HandleSchedExec        *ebpf.Program `ebpf:"handle_sched_exec"`
	HandleSysEnterClone    *ebpf.Program `ebpf:"handle_sys_enter_clone"`
	HandleSysEnterClone3   *ebpf.Program `ebpf:"handle_sys_enter_clone3"`
	HandleSysEnterConnect  *ebpf.Program `ebpf:"handle_sys_enter_connect"`
	HandleSysEnterExecve   *ebpf.Program `ebpf:"handle_sys_enter_execve"`
	HandleSysEnterExecveat *ebpf.Program `ebpf:"handle_sys_enter_execveat"`
	HandleSysEnterOpen     *ebpf.Program `ebpf:"handle_sys_enter_open"`
	HandleSysEnterOpenat   *ebpf.Program `ebpf:"handle_sys_enter_openat"`
	HandleSysEnterUnshare  *ebpf.Program `ebpf:"handle_sys_enter_unshare"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.HandleSchedExec,
		p.HandleSysEnterClone,
		p.HandleSysEnterClone3,
		p.HandleSysEnterConnect,
		p.HandleSysEnterExecve,
		p.HandleSysEnterExecveat,
		p.HandleSysEnterOpen,
		p.HandleSysEnterOpenat,
		p.HandleSysEnterUnshare,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfel.o
var _ProbeBytes []byte
