// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type probePendingEvent struct {
	_         structs.HostLayout
	EventType uint32
	Pad       uint32
	Raw       [512]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	probeMapDrops               = "drops"
	probeMapEvents              = "events"
	probeMapPending             = "pending"
	probeMapPendingScratch      = "pending_scratch"
	probeProgHandleDoInitModule = "handle_do_init_module"
	probeProgHandleRawSysEnter  = "handle_raw_sys_enter"
	probeProgHandleRawSysExit   = "handle_raw_sys_exit"
	probeProgHandleSchedExec    = "handle_sched_exec"
)

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	HandleDoInitModule *ebpf.ProgramSpec `ebpf:"handle_do_init_module"`
	HandleRawSysEnter  *ebpf.ProgramSpec `ebpf:"handle_raw_sys_enter"`
	HandleRawSysExit   *ebpf.ProgramSpec `ebpf:"handle_raw_sys_exit"`
	HandleSchedExec    *ebpf.ProgramSpec `ebpf:"handle_sched_exec"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	Drops          *ebpf.MapSpec `ebpf:"drops"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	Pending        *ebpf.MapSpec `ebpf:"pending"`
	PendingScratch *ebpf.MapSpec `ebpf:"pending_scratch"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	Drops          *ebpf.Map `ebpf:"drops"`
	Events         *ebpf.Map `ebpf:"events"`
	Pending        *ebpf.Map `ebpf:"pending"`
	PendingScratch *ebpf.Map `ebpf:"pending_scratch"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.Drops,
		m.Events,
		m.Pending,
		m.PendingScratch,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	HandleDoInitModule *ebpf.Program `ebpf:"handle_do_init_module"`
	HandleRawSysEnter  *ebpf.Program `ebpf:"handle_raw_sys_enter"`
	HandleRawSysExit   *ebpf.Program `ebpf:"handle_raw_sys_exit"`
	HandleSchedExec    *ebpf.Program `ebpf:"handle_sched_exec"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.HandleDoInitModule,
		p.HandleRawSysEnter,
		p.HandleRawSysExit,
		p.HandleSchedExec,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfeb.o
var _ProbeBytes []byte
